package day45_exceptionHandling;

public class BadArray {
	
	public static void main(String[] args) {
		
		int[] number = {1,2,3};
		
		for(int i=0;i<=number.length;i++) {
			System.out.println(number[i]);
		}
		
		System.out.println("Learning exception");
		
	}

}
